-- ========================================================
-- MAGIC PROMPTS — COMPLETE SUPABASE DATABASE & AUTH SQL SCHEMA
-- ========================================================
-- Copy and paste this script directly into your Supabase SQL Editor:
-- Dashboard -> SQL Editor -> New Query -> Run
-- ========================================================

-- 1. Enable Required Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  icon TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Models Table
CREATE TABLE IF NOT EXISTS public.models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Prompts Table
CREATE TABLE IF NOT EXISTS public.prompts (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  model TEXT NOT NULL,
  description TEXT NOT NULL,
  prompt TEXT NOT NULL,
  negative TEXT,
  tags TEXT[] NOT NULL,
  aspect TEXT NOT NULL,
  image_url TEXT NOT NULL,
  ratio DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  views INTEGER NOT NULL DEFAULT 0,
  likes INTEGER NOT NULL DEFAULT 0,
  copies INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Profiles Table (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'user'::text NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5b. Create User Boards Table (Pinterest Style)
CREATE TABLE IF NOT EXISTS public.user_boards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, name)
);

-- 5c. Create Saved Prompts Table
CREATE TABLE IF NOT EXISTS public.saved_prompts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  prompt_id TEXT REFERENCES public.prompts(id) ON DELETE CASCADE,
  board_name TEXT DEFAULT 'All Saved',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, prompt_id, board_name)
);

-- 6. Enable Row Level Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_boards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_prompts ENABLE ROW LEVEL SECURITY;

-- 7. Create RLS Policies
-- Public Read Access Policies
DROP POLICY IF EXISTS "Allow public read access on categories" ON public.categories;
CREATE POLICY "Allow public read access on categories" ON public.categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access on models" ON public.models;
CREATE POLICY "Allow public read access on models" ON public.models FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access on prompts" ON public.prompts;
CREATE POLICY "Allow public read access on prompts" ON public.prompts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access on profiles" ON public.profiles;
CREATE POLICY "Allow public read access on profiles" ON public.profiles FOR SELECT USING (true);

-- Authenticated Admin Write Access Policies
DROP POLICY IF EXISTS "Allow admin write access on categories" ON public.categories;
CREATE POLICY "Allow admin write access on categories" ON public.categories FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write access on models" ON public.models;
CREATE POLICY "Allow admin write access on models" ON public.models FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin write access on prompts" ON public.prompts;
CREATE POLICY "Allow admin write access on prompts" ON public.prompts FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow user write access on profiles" ON public.profiles;
CREATE POLICY "Allow user write access on profiles" ON public.profiles FOR ALL TO authenticated USING (auth.uid() = id);

-- 8. Register & Confirm Admin User Safely in Supabase Auth
-- Email: anupam.dev81@gmail.com | Password: Sonu9014@
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'anupam.dev81@gmail.com') THEN
    INSERT INTO auth.users (
      instance_id,
      id,
      aud,
      role,
      email,
      encrypted_password,
      email_confirmed_at,
      raw_app_meta_data,
      raw_user_meta_data,
      created_at,
      updated_at
    ) VALUES (
      '00000000-0000-0000-0000-000000000000',
      'b7e88f1f-9a3c-411b-a51a-5c1421cfa5d3',
      'authenticated',
      'authenticated',
      'anupam.dev81@gmail.com',
      crypt('Sonu9014@', gen_salt('bf')),
      now(),
      '{"provider": "email", "providers": ["email"]}',
      '{"full_name": "Anupam Admin", "role": "admin"}',
      now(),
      now()
    );
  ELSE
    UPDATE auth.users
    SET encrypted_password = crypt('Sonu9014@', gen_salt('bf')),
        email_confirmed_at = now(),
        raw_user_meta_data = '{"full_name": "Anupam Admin", "role": "admin"}'
    WHERE email = 'anupam.dev81@gmail.com';
  END IF;
END $$;

-- Insert Admin Profile Record
INSERT INTO public.profiles (id, email, full_name, role)
SELECT id, email, 'Anupam Admin', 'admin'
FROM auth.users
WHERE email = 'anupam.dev81@gmail.com'
ON CONFLICT (id) DO UPDATE SET role = 'admin';

-- 9. Insert Seed Categories
INSERT INTO public.categories (name, slug, icon, description) VALUES
  ('All', 'all', 'Sparkles', 'Explore the entire prompt library containing professional visual triggers.'),
  ('E-commerce', 'ecommerce', 'ShoppingBag', 'Commercial style, high-end product renders, mockups, and cosmetic showcases.'),
  ('Photo Editing', 'photo-editing', 'Aperture', 'Color grading prompts, photo retouches, double exposures, and visual corrections.'),
  ('Portrait & Avatar', 'portrait-avatar', 'User', 'Ultra-realistic human profiles, photorealistic avatars, and high-fidelity face studies.'),
  ('Character Design', 'character-design', 'Swords', 'Fantasy warriors, sci-fi cybernetic entities, game skins, and detailed outfit designs.'),
  ('Anime & Cartoon', 'anime-cartoon', 'Star', 'Studio Ghibli styles, modern anime visual filters, keyframes, and retro cartoons.'),
  ('Art Style', 'art-style', 'Palette', 'Classic oil canvas paintings, watercolors, line sketches, and abstract expressionist textures.'),
  ('Interior Design', 'interior-design', 'Sofa', 'Modern living spaces, luxury architectural designs, Scandinavian apartments, and room layouts.'),
  ('Visual Effects', 'visual-effects', 'Wand2', 'Double exposures, neon glows, particulate magic spells, motion blurs, and holographic filters.')
ON CONFLICT (name) DO NOTHING;

-- 10. Insert Seed Models
INSERT INTO public.models (name) VALUES
  ('ChatGPT Images'),
  ('Gemini'),
  ('Midjourney'),
  ('Flux'),
  ('Leonardo AI'),
  ('Stable Diffusion'),
  ('Adobe Firefly'),
  ('Ideogram'),
  ('Recraft')
ON CONFLICT (name) DO NOTHING;

-- 11. Insert Seed Prompts
INSERT INTO public.prompts (id, slug, title, category, model, description, prompt, negative, tags, aspect, image_url, ratio, views, likes, copies) VALUES
  ('1', 'cinematic-luxury-watch-photography', 'Cinematic Luxury Watch Photography', 'E-commerce', 'Midjourney', 'Editorial-grade product shot with dramatic light and gold reflections.', 'Cinematic luxury watch photography, close-up of a gold Rolex on dark marble surface, dramatic side lighting, soft shadows, extremely detailed macro shot, 8k, editorial fashion campaign, shallow depth of field', 'blurry, cartoon, low quality, watermark, text', ARRAY['luxury', 'product', 'watch', 'editorial'], '4:5', 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&q=80&w=800', 1.25, 24800, 1820, 942),
  ('2', 'iridescent-holographic-portrait', 'Iridescent Holographic Portrait', 'Portrait & Avatar', 'Flux', 'High fashion editorial portrait with holographic makeup and studio light.', 'Ethereal portrait of a woman with holographic iridescent makeup, dewy skin, studio lighting with soft magenta and cyan rim lights, high fashion editorial photography, hasselblad, 85mm, ultra detailed', 'blurry, distorted, lowres, text', ARRAY['portrait', 'fashion', 'holographic', 'editorial'], '4:5', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800', 1.35, 31200, 2410, 1150),
  ('3', 'neon-tokyo-anime-girl', 'Neon Tokyo Anime Girl', 'Anime & Cartoon', 'Leonardo AI', 'Kawaii anime portrait against a rainy neon Tokyo street.', 'Anime girl with pink pastel hair and headphones, cyberpunk neon Tokyo street background, colorful signage, cinematic composition, high detail, studio ghibli lighting mixed with cyberpunk', 'blurry, bad anatomy, deformed', ARRAY['anime', 'cyberpunk', 'portrait'], '4:5', 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&q=80&w=800', 1.28, 18400, 1450, 720),
  ('4', 'wabi-sabi-golden-hour-interior', 'Wabi-Sabi Golden Hour Interior', 'Interior Design', 'Midjourney', 'Minimal luxury interior with warm sunset light and organic forms.', 'Minimalist luxury interior, curved cream sofa, warm sunset light through floor-to-ceiling windows, wabi-sabi aesthetic, natural materials, architectural photography, magazine quality', 'ugly, noisy, low quality, bad lighting', ARRAY['interior', 'architecture', 'minimal'], '16:9', 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&q=80&w=800', 0.9, 12900, 980, 512),
  ('5', 'floating-perfume-splash', 'Floating Perfume Splash', 'E-commerce', 'Ideogram', 'Levitating perfume bottle with a poetic liquid splash on pastel.', 'Levitating clear perfume bottle with dynamic peach liquid splash, soft pastel pink background, commercial product photography, high-key lighting, luxury cosmetics campaign', 'unfocused, dark, low resolution', ARRAY['product', 'cosmetics', 'splash'], '4:5', 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800', 1.4, 22100, 1620, 840),
  ('6', 'epic-fantasy-warrior-concept', 'Epic Fantasy Warrior Concept', 'Character Design', 'Stable Diffusion', 'Dramatic character concept art with ornate armor and backlight.', 'Fantasy warrior character concept art, ornate obsidian armor with gold trim, dramatic rim light, atmospheric fog, digital painting, artstation trending, wlop style', 'sketch, plain, low detail', ARRAY['character', 'fantasy', 'concept'], '4:5', 'https://images.unsplash.com/photo-1519074002996-a69e7ac46a42?auto=format&fit=crop&q=80&w=800', 1.37, 15600, 1240, 610),
  ('7', 'isometric-dreamy-island', 'Isometric Dreamy Island', 'Art Style', 'Midjourney', 'Cinema 4D-style floating island in soft pastel palette.', '3D isometric floating island with waterfalls and tiny ruins, soft pastel pink background, cinema 4d octane render, clay materials, dreamy soft lighting', 'photorealistic, dark, gritty', ARRAY['3d', 'isometric', 'render'], '1:1', 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&q=80&w=800', 1.12, 9800, 720, 380),
  ('8', 'liquid-chrome-sculpture', 'Liquid Chrome Sculpture', 'Visual Effects', 'Flux', 'Iridescent liquid chrome form on clean studio white.', 'Abstract liquid chrome sculpture with iridescent purple and blue reflections, studio white background, hyper-detailed, product render, octane, y2k aesthetic', 'blurry, complex background, text', ARRAY['3d', 'abstract', 'chrome'], '4:5', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800', 1.25, 14200, 1080, 490)
ON CONFLICT (id) DO NOTHING;
